from . import __version__ as app_version

app_name = "paddy_procurement"
app_title = "Paddy Procurement"
app_publisher = "Generated by ChatGPT"
app_description = "Paddy procurement & GRN automation for ERPNext"
app_email = "you@example.com"
app_license = "MIT"

doc_events = {
    "Weighbridge Entry": {
        "validate": "paddy_procurement.doctype.weighbridge_entry.weighbridge_entry.WeighbridgeEntry.validate",
        "on_submit": "paddy_procurement.doctype.weighbridge_entry.weighbridge_entry.WeighbridgeEntry.on_submit"
    },
    "Paddy QC": {
        "validate": "paddy_procurement.doctype.paddy_qc.paddy_qc.PaddyQC.validate",
        "on_submit": "paddy_procurement.doctype.paddy_qc.paddy_qc.PaddyQC.on_submit"
    }
}

override_whitelisted_methods = {
    "paddy_procurement.api.receive_weighbridge": "paddy_procurement.api.receive_weighbridge"
}

scheduler_events = {
    "hourly": [
        "paddy_procurement.tasks.hourly_weighbridge_sync"
    ]
}
