from __future__ import unicode_literals
from frappe import _
app_name = "paddy_procurement"
app_title = "Paddy Procurement"
app_publisher = "Generated by ChatGPT"
app_description = "Paddy procurement & GRN automation for ERPNext"
app_email = "you@example.com"
app_license = "MIT"
